//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class order_form
    {

        [DisplayName("訂單編號")]
        [Required]
        public int order_id { get; set; }

        [DisplayName("訂單日期")]
        [Required]
        public Nullable<System.DateTime> order_date { get; set; }

        [DisplayName("收件人姓名")]
        [Required]
        public string recipient_name { get; set; }

        [DisplayName("收件人電話")]
        [Required]
        public string recipient_phone { get; set; }

        [DisplayName("收件人地址")]
        [Required]
        public string recipient_address { get; set; }

        [DisplayName("付款方式")]
        public string payment_method { get; set; }

        [DisplayName("匯款帳號")]
        [Required]
        public string remittance_account { get; set; }

        [DisplayName("付款狀態")]
        public string payment_status { get; set; }

        [DisplayName("匯款狀態")]
        public string shipping_status { get; set; }

        [DisplayName("會員帳號")]
        [Required]
        public string member_account { get; set; }

        [DisplayName("備註")]
        public string remark { get; set; }
    }
}
