//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_form
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order_form()
        {
            this.order_detail = new HashSet<order_detail>();
        }
    
        public int order_id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public string recipient_name { get; set; }
        public string recipient_phone { get; set; }
        public string recipient_address { get; set; }
        public string payment_method { get; set; }
        public string remittance_account { get; set; }
        public string payment_status { get; set; }
        public string shipping_status { get; set; }
        public string member_account { get; set; }
        public string remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_detail> order_detail { get; set; }
    }
}
