//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_detail
    {
        public Nullable<int> order_id { get; set; }
        public Nullable<int> product_quantity { get; set; }
        public string product_no { get; set; }
        public int rowid { get; set; }
    
        public virtual order_form order_form { get; set; }
    }
}
