//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class order_detail
    {

        [DisplayName("訂單編號")]
        public int order_id { get; set; }

        [DisplayName("商品數量")]
        public Nullable<int> product_quantity { get; set; }

        [DisplayName("商品編號")]
        public string product_no { get; set; }
        public int rowid { get; set; }

        public virtual order_form order_form { get; set; }
        public virtual product product { get; set; }
    }
}
