//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.shopping_cart = new HashSet<shopping_cart>();
        }

        [DisplayName("產品編號")]
        [Required]
        public string product_no { get; set; }

        [DisplayName("產品名稱")]
        [Required]
        public string product_name { get; set; }

        [DisplayName("產品價格")]
        [Required]
        public Nullable<int> product_price { get; set; }

        [DisplayName("產品描述")]
        [Required]
        public string product_description { get; set; }

        [DisplayName("產品介紹")]
        [Required]
        public string product_details { get; set; }

        [DisplayName("產品圖片")]
        [Required]
        public string product_image { get; set; }

        [DisplayName("產品分類")]
        [Required]
        public string Product_catagory { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shopping_cart> shopping_cart { get; set; }
    }
}
